// <auto-generated />
using System;
using ContactBookApplication.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactBookApplication.Migrations
{
    [DbContext(typeof(ContactBookContext))]
    [Migration("20210523122135_AddedDateTimeOfCreationToContact")]
    partial class AddedDateTimeOfCreationToContact
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("ContactBookApplication.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = "e674705e-7348-4a8c-8f9d-bd9e88c306ac",
                            City = "Aja",
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            Country = "Nigeria",
                            State = "Lagos",
                            StreetName = "Asajon",
                            StreetNumber = "7"
                        },
                        new
                        {
                            Id = "c603a05c-7479-41ea-b57f-851c0787dea2",
                            City = "Mubi",
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            Country = "Nigeria",
                            PostCode = "1233234",
                            State = "Adamawa",
                            StreetName = "Adsu Staff Quaters",
                            StreetNumber = "36"
                        },
                        new
                        {
                            Id = "f8ed45ad-2647-41da-8021-e30b39c02b4c",
                            City = "Jalingo",
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Country = "Nigeria",
                            PostCode = "56342",
                            State = "Taraba",
                            StreetName = "Goverment House",
                            StreetNumber = "16"
                        },
                        new
                        {
                            Id = "c2d62492-1422-4c96-b0d2-db1eaa198253",
                            City = "Queens",
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Country = "USA",
                            PostCode = "32344",
                            State = "New York",
                            StreetName = "South side",
                            StreetNumber = "5"
                        },
                        new
                        {
                            Id = "111c1a8a-a7a8-4b6f-8c89-6d22021d05d9",
                            City = "Beverly Hills",
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Country = "USA",
                            PostCode = "34231",
                            State = "Carlifonia",
                            StreetName = "Angels",
                            StreetNumber = "5"
                        },
                        new
                        {
                            Id = "d7509484-f2cf-4af9-8923-624584f8f003",
                            City = "Owerri Municipal",
                            ContactId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Country = "Nigeria",
                            PostCode = "34231",
                            State = "Imo",
                            StreetName = "Okigwe",
                            StreetNumber = "5"
                        });
                });

            modelBuilder.Entity("ContactBookApplication.Models.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ContactBookApplication.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salutation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            Company = "decagon",
                            CompanyEmail = "victor.iliya@decagon.com",
                            DateOfCreation = new DateTime(2021, 5, 23, 12, 21, 35, 82, DateTimeKind.Utc).AddTicks(7562),
                            FirstName = "Victor",
                            OtherName = "B",
                            PictureUrl = "victor.jpg",
                            Salutation = "Mr.",
                            SecondName = "Iliya",
                            Website = "hhtps://victoriliya.com"
                        },
                        new
                        {
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Company = "decagon",
                            CompanyEmail = "young@decagon.com",
                            DateOfCreation = new DateTime(2021, 5, 23, 12, 21, 35, 84, DateTimeKind.Utc).AddTicks(627),
                            FirstName = "Solomon",
                            OtherName = "",
                            PictureUrl = "solomon.jpg",
                            Salutation = "Mr.",
                            SecondName = "Young",
                            Website = "hhtps://young.com"
                        },
                        new
                        {
                            ContactId = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            Company = "Roc Nation",
                            CompanyEmail = "jigga@rocnation.com",
                            DateOfCreation = new DateTime(2021, 5, 23, 12, 21, 35, 84, DateTimeKind.Utc).AddTicks(903),
                            FirstName = "Shawn",
                            NickName = "Jay-Z",
                            OtherName = "",
                            PictureUrl = "ugee.jpg",
                            Salutation = "Mr.",
                            SecondName = "Carter",
                            Website = "hhtps://ugee.com"
                        },
                        new
                        {
                            ContactId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Company = "decagon",
                            CompanyEmail = "ugee@decagon.com",
                            DateOfCreation = new DateTime(2021, 5, 23, 12, 21, 35, 84, DateTimeKind.Utc).AddTicks(1587),
                            FirstName = "Ugee",
                            OtherName = "",
                            PictureUrl = "ugee.jpg",
                            Salutation = "Mr.",
                            SecondName = "Umeoke",
                            Website = "hhtps://ugee.com"
                        });
                });

            modelBuilder.Entity("ContactBookApplication.Models.EmailAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            Email = "victorbiliya@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            Email = "vick@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            ContactId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Email = "ugee@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Email = "young@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            Email = "hov@gmail.com"
                        });
                });

            modelBuilder.Entity("ContactBookApplication.Models.PhoneNumber", b =>
                {
                    b.Property<int>("PhoneNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.HasKey("PhoneNumberId");

                    b.HasIndex("ContactId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            PhoneNumberId = 1,
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            CountryCode = "234",
                            Number = "7034192342"
                        },
                        new
                        {
                            PhoneNumberId = 2,
                            ContactId = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            CountryCode = "234",
                            Number = "813344567"
                        },
                        new
                        {
                            PhoneNumberId = 3,
                            ContactId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CountryCode = "234",
                            Number = "9032456783"
                        },
                        new
                        {
                            PhoneNumberId = 4,
                            ContactId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CountryCode = "234",
                            Number = "9133456432"
                        },
                        new
                        {
                            PhoneNumberId = 6,
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            CountryCode = "234",
                            Number = "8063445467"
                        },
                        new
                        {
                            PhoneNumberId = 7,
                            ContactId = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            CountryCode = "1",
                            Number = "5352323433"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ContactBookApplication.Models.Address", b =>
                {
                    b.HasOne("ContactBookApplication.Models.Contact", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ContactBookApplication.Models.EmailAddress", b =>
                {
                    b.HasOne("ContactBookApplication.Models.Contact", null)
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactBookApplication.Models.PhoneNumber", b =>
                {
                    b.HasOne("ContactBookApplication.Models.Contact", "Contact")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ContactBookApplication.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ContactBookApplication.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactBookApplication.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ContactBookApplication.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactBookApplication.Models.Contact", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Emails");

                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
